name: "Sensitive workflow"
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Run"
        run: |
          echo "Hello, world! ${{ env.MY_SECRET }}"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
